### ISSUE TITLE
Handle rate limiting

### ISSUE THREAD

**Issue by williamsdb** [williamsdb/php2Bluesky#17]
Placeholder to handle rate limiting in code.

**Comment by MaFtX** [comment]
I'm getting this when it's trying to create a new session (any idea what the limit is?). I noticed there's a 'refreshSession' function and I'm wondering if that's something I should be using?

My use case is that I create a post when there's a new 'item' but each post is 2 minutes apart. There could be up to 20 to post at a time so spread out over 40mins in that instance. Is it because each post is creating a new session rather than checking for an existing one?

**Comment by williamsdb** [comment]
Hi, you say that you are getting "this" but don't actually say what "this" is! Are you getting an error message? If so can you paste it here so I can take a look please? Also a snippet of your code would be good too. Thanks

**Comment by MaFtX** [comment]
Sorry, I meant getting the rate limiting (I assumed this was what the Issue was referring to? I don't really use GitHub to be honest...)

PHP Error log here:

[17-Dec-2024 22:13:19 UTC] PHP Fatal error:  Uncaught RuntimeException: Rate Limit Exceeded in /home/[redacted]/public_html/bluesky/BlueskyApi.php:244
Stack trace:
#0 /home/[redacted]/public_html/bluesky/BlueskyApi.php(36): cjrasmussen\BlueskyApi\BlueskyApi->startNewSession()
#1 /home/[redacted]/public_html/bluesky/functions.php(13): cjrasmussen\BlueskyApi\BlueskyApi->auth()
#2 /home/[redacted]/public_html/bluesky/postbluesky.php(57): bluesky_connect()
#3 {main}
  thrown in /home/[redacted]/public_html/bluesky/BlueskyApi.php on line 244

According to this:  https://github.com/bluesky-social/atproto/discussions/2818   there is a limit of 100 'logins' (com.atproto.server.createSession) per day so I suspect I hit that limit while I was testing creating posts. As every time I create a post it creates a new session/login. Hence why I was asking about how to use the refreshSession function.

**Comment by williamsdb** [comment]
Hi

Thanks for that I was really just checking that we were talking about the same thing. This error is being thrown from cjrasmussen\BlueskyApi rather than my own code but the issue is the same. 

It's difficult to tell from the response but I suspect that you are hitting the 300 sessions a day limit. If you [have a look here](https://docs.bsky.app/docs/advanced-guides/rate-limits) you can read more about the limits that might be affecting you. What you then do about it will somewhat depend on your use case.

Regarding this ticket what my code will eventually do is trap this error and return so more information to help you debug. Hopefully, that will be this year but I'm running out of time!

**Comment by MaFtX** [comment]
In case anyone else comes across this, here's how I worked around it:

I replaced 
```
// connect to Bluesky API
$connection = bluesky_connect($handle, $password);
```

with

```
$connection = new BlueskyApi();
$blueskyApiSessionHelper = new BlueskyApiSessionHelper($connection);

try {
	$blueskyApiSessionHelper->auth("../../blueskytoken.txt", $handle, $password);
} catch (Exception $e) {
	// TODO: Handle the exception however you want
}
	
//get/update refresh token to use later (rate limit 100 new connections per day)
$refresh_token = $connection->getRefreshToken();
file_put_contents("../../blueskytoken.txt", $refresh_token);
```

I also had two instances of creating the connection in my code, essentially halving my available sessions!! But that was my error, not yours!!

**Comment by williamsdb** [comment]
Ok thanks for the update. That's actually nothing to do with my code as that's all in [BlueskyApi](https://github.com/cjrasmussen/BlueskyApi) which is the library I use that actually sends the command to Bluesky. BlueskyApiSessionHelper is new as that's not in the version I have on my server. I do need to update it to the latest version to ensure that it still works.

**Comment by MaFtX** [comment]
`$connection = bluesky_connect($handle, $password);`
Is from your code though? That's what I replaced

**Comment by williamsdb** [comment]
yep it's in the file of examples. I have changed the name of the file from index.php to examples.php to make that clearer.

Basically you can use Clark Rasmussen's [BlueskyApi](https://github.com/cjrasmussen/BlueskyApi) without my code and post directly using that but you cannot use my code without [BlueskyApi](https://github.com/cjrasmussen/BlueskyApi). Clark's code handles tokens and the connection while my code is a wrapper making it easy to post images and text to Bluesky handling URLs, hashtags etc., something Clark's code doesn't do.

That's what I meant about it not being my code - token management is part of the connection code with is in Clark's library (and is described there). I've updated the readme to make that clearer (I hope!)
